create table if not exists users (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  email varchar(255) not null unique
);

create table if not exists items (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  description varchar(1000) not null,
  available boolean not null,
  owner_id bigint not null,
  request_id bigint,
  constraint fk_items_owner foreign key (owner_id) references users(id)
);

create table if not exists requests (
  id bigint generated by default as identity primary key,
  description varchar(1000) not null,
  requester_id bigint not null,
  created timestamp not null,
  constraint fk_requests_requester foreign key (requester_id) references users(id)
);

create table if not exists bookings (
  id bigint generated by default as identity primary key,
  start_time timestamp not null,
  end_time   timestamp not null,
  item_id    bigint not null,
  booker_id  bigint not null,
  status     varchar(16) not null,
  constraint fk_bookings_item foreign key (item_id) references items(id),
  constraint fk_bookings_booker foreign key (booker_id) references users(id)
);